
# End generated by rel-engage
# ---------------------------
LOCAL_BOLT_URL=bolt://localhost:7687
NEO4J_VERSION=3.5.0


# Building and running

## Builds browser files for tc-ui (in watch mode when local)
build-statics:
	@if [ -z $(CI) ]; \
		then $(info Webpack bundling modules ...) webpack --mode=development --watch; \
		else $(info Webpack bundling modules ...) webpack --mode=production; \
	fi

run-db:
	docker-compose up

run-app:
	NEO4J_BOLT_URL=${LOCAL_BOLT_URL} \
	TREECREEPER_TEST=true \
	TREECREEPER_SCHEMA_DIRECTORY=schema \
	nodemon --inspect src/app.js

run:
	@concurrently "make run-db" "make run-app" "make build-statics"

install-db:
	docker-compose up --no-start
	./scripts/neo4j-plugins.sh

install:
	@concurrently "npm install" "make install-db"
